version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - net
    volumes:
      - mongo-data:/var/lib/mysql/data

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongodb:27017/
    networks:
      - net

  celery-tester:
    container_name: celery-tester
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - net

volumes:
  mongo-data:
    driver: local

networks:
  net:
    driver: bridge