version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - net
    volumes:
      - mongo-data:/var/lib/mysql/data

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongodb:27017/
    networks:
      - net

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - net

  celery-tester:
    container_name: celery-tester
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - mongodb
      - redis
    networks:
      - net

  worker:
    build: .
    command: celery --app app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - celery-tester
      - redis
    networks:
      - net

volumes:
  mongo-data:
    driver: local

networks:
  net:
    driver: bridge